/**
 * Copyright (c) 2015-2017 Obeo, Inria
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 	
 * Contributors:
 * - William Piers <william.piers@obeo.fr>
 * - Philippe Merle <philippe.merle@inria.fr>
 * - Faiez Zalila <faiez.zalila@inria.fr>
 */
package org.eclipse.cmf.occi.tosca.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.cmf.occi.tosca.util.ToscaAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ToscaItemProviderAdapterFactory extends ToscaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ToscaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayString} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayStringItemProvider arrayStringItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayStringAdapter() {
		if (arrayStringItemProvider == null) {
			arrayStringItemProvider = new arrayStringItemProvider(this);
		}

		return arrayStringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayBoolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayBooleanItemProvider arrayBooleanItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayBoolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayBooleanAdapter() {
		if (arrayBooleanItemProvider == null) {
			arrayBooleanItemProvider = new arrayBooleanItemProvider(this);
		}

		return arrayBooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayByte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayByteItemProvider arrayByteItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayByte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayByteAdapter() {
		if (arrayByteItemProvider == null) {
			arrayByteItemProvider = new arrayByteItemProvider(this);
		}

		return arrayByteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayDouble} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayDoubleItemProvider arrayDoubleItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayDouble}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayDoubleAdapter() {
		if (arrayDoubleItemProvider == null) {
			arrayDoubleItemProvider = new arrayDoubleItemProvider(this);
		}

		return arrayDoubleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayFloat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayFloatItemProvider arrayFloatItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayFloat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayFloatAdapter() {
		if (arrayFloatItemProvider == null) {
			arrayFloatItemProvider = new arrayFloatItemProvider(this);
		}

		return arrayFloatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayInteger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayIntegerItemProvider arrayIntegerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayInteger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayIntegerAdapter() {
		if (arrayIntegerItemProvider == null) {
			arrayIntegerItemProvider = new arrayIntegerItemProvider(this);
		}

		return arrayIntegerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayLongItemProvider arrayLongItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayLongAdapter() {
		if (arrayLongItemProvider == null) {
			arrayLongItemProvider = new arrayLongItemProvider(this);
		}

		return arrayLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.arrayShort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayShortItemProvider arrayShortItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.arrayShort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayShortAdapter() {
		if (arrayShortItemProvider == null) {
			arrayShortItemProvider = new arrayShortItemProvider(this);
		}

		return arrayShortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.toscadatatypesnetworkNetworkInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected toscadatatypesnetworkNetworkInfoItemProvider toscadatatypesnetworkNetworkInfoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.toscadatatypesnetworkNetworkInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtoscadatatypesnetworkNetworkInfoAdapter() {
		if (toscadatatypesnetworkNetworkInfoItemProvider == null) {
			toscadatatypesnetworkNetworkInfoItemProvider = new toscadatatypesnetworkNetworkInfoItemProvider(this);
		}

		return toscadatatypesnetworkNetworkInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.toscadatatypesnetworkPortInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected toscadatatypesnetworkPortInfoItemProvider toscadatatypesnetworkPortInfoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.toscadatatypesnetworkPortInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtoscadatatypesnetworkPortInfoAdapter() {
		if (toscadatatypesnetworkPortInfoItemProvider == null) {
			toscadatatypesnetworkPortInfoItemProvider = new toscadatatypesnetworkPortInfoItemProvider(this);
		}

		return toscadatatypesnetworkPortInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.toscadatatypesCredential} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected toscadatatypesCredentialItemProvider toscadatatypesCredentialItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.toscadatatypesCredential}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtoscadatatypesCredentialAdapter() {
		if (toscadatatypesCredentialItemProvider == null) {
			toscadatatypesCredentialItemProvider = new toscadatatypesCredentialItemProvider(this);
		}

		return toscadatatypesCredentialItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.toscadatatypesnetworkPortSpec} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected toscadatatypesnetworkPortSpecItemProvider toscadatatypesnetworkPortSpecItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.toscadatatypesnetworkPortSpec}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtoscadatatypesnetworkPortSpecAdapter() {
		if (toscadatatypesnetworkPortSpecItemProvider == null) {
			toscadatatypesnetworkPortSpecItemProvider = new toscadatatypesnetworkPortSpecItemProvider(this);
		}

		return toscadatatypesnetworkPortSpecItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_rootItemProvider tosca_capabilities_rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_rootAdapter() {
		if (tosca_capabilities_rootItemProvider == null) {
			tosca_capabilities_rootItemProvider = new Tosca_capabilities_rootItemProvider(this);
		}

		return tosca_capabilities_rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_node} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_nodeItemProvider tosca_capabilities_nodeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_node}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_nodeAdapter() {
		if (tosca_capabilities_nodeItemProvider == null) {
			tosca_capabilities_nodeItemProvider = new Tosca_capabilities_nodeItemProvider(this);
		}

		return tosca_capabilities_nodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_endpointItemProvider tosca_capabilities_endpointItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_endpointAdapter() {
		if (tosca_capabilities_endpointItemProvider == null) {
			tosca_capabilities_endpointItemProvider = new Tosca_capabilities_endpointItemProvider(this);
		}

		return tosca_capabilities_endpointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_scalable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_scalableItemProvider tosca_capabilities_scalableItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_scalable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_scalableAdapter() {
		if (tosca_capabilities_scalableItemProvider == null) {
			tosca_capabilities_scalableItemProvider = new Tosca_capabilities_scalableItemProvider(this);
		}

		return tosca_capabilities_scalableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_network_bindable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_network_bindableItemProvider tosca_capabilities_network_bindableItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_network_bindable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_network_bindableAdapter() {
		if (tosca_capabilities_network_bindableItemProvider == null) {
			tosca_capabilities_network_bindableItemProvider = new Tosca_capabilities_network_bindableItemProvider(this);
		}

		return tosca_capabilities_network_bindableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_container} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_containerItemProvider tosca_capabilities_containerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_container}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_containerAdapter() {
		if (tosca_capabilities_containerItemProvider == null) {
			tosca_capabilities_containerItemProvider = new Tosca_capabilities_containerItemProvider(this);
		}

		return tosca_capabilities_containerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint_database} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_endpoint_databaseItemProvider tosca_capabilities_endpoint_databaseItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint_database}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_endpoint_databaseAdapter() {
		if (tosca_capabilities_endpoint_databaseItemProvider == null) {
			tosca_capabilities_endpoint_databaseItemProvider = new Tosca_capabilities_endpoint_databaseItemProvider(this);
		}

		return tosca_capabilities_endpoint_databaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint_public} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_endpoint_publicItemProvider tosca_capabilities_endpoint_publicItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint_public}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_endpoint_publicAdapter() {
		if (tosca_capabilities_endpoint_publicItemProvider == null) {
			tosca_capabilities_endpoint_publicItemProvider = new Tosca_capabilities_endpoint_publicItemProvider(this);
		}

		return tosca_capabilities_endpoint_publicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint_admin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_endpoint_adminItemProvider tosca_capabilities_endpoint_adminItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_endpoint_admin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_endpoint_adminAdapter() {
		if (tosca_capabilities_endpoint_adminItemProvider == null) {
			tosca_capabilities_endpoint_adminItemProvider = new Tosca_capabilities_endpoint_adminItemProvider(this);
		}

		return tosca_capabilities_endpoint_adminItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_operatingsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_operatingsystemItemProvider tosca_capabilities_operatingsystemItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_operatingsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_operatingsystemAdapter() {
		if (tosca_capabilities_operatingsystemItemProvider == null) {
			tosca_capabilities_operatingsystemItemProvider = new Tosca_capabilities_operatingsystemItemProvider(this);
		}

		return tosca_capabilities_operatingsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_attachment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_attachmentItemProvider tosca_capabilities_attachmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_capabilities_attachment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_attachmentAdapter() {
		if (tosca_capabilities_attachmentItemProvider == null) {
			tosca_capabilities_attachmentItemProvider = new Tosca_capabilities_attachmentItemProvider(this);
		}

		return tosca_capabilities_attachmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_rootItemProvider tosca_nodes_rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_rootAdapter() {
		if (tosca_nodes_rootItemProvider == null) {
			tosca_nodes_rootItemProvider = new Tosca_nodes_rootItemProvider(this);
		}

		return tosca_nodes_rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_webapplication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_webapplicationItemProvider tosca_nodes_webapplicationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_webapplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_webapplicationAdapter() {
		if (tosca_nodes_webapplicationItemProvider == null) {
			tosca_nodes_webapplicationItemProvider = new Tosca_nodes_webapplicationItemProvider(this);
		}

		return tosca_nodes_webapplicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_softwarecomponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_softwarecomponentItemProvider tosca_nodes_softwarecomponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_softwarecomponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_softwarecomponentAdapter() {
		if (tosca_nodes_softwarecomponentItemProvider == null) {
			tosca_nodes_softwarecomponentItemProvider = new Tosca_nodes_softwarecomponentItemProvider(this);
		}

		return tosca_nodes_softwarecomponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_dbms} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_dbmsItemProvider tosca_nodes_dbmsItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_dbms}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_dbmsAdapter() {
		if (tosca_nodes_dbmsItemProvider == null) {
			tosca_nodes_dbmsItemProvider = new Tosca_nodes_dbmsItemProvider(this);
		}

		return tosca_nodes_dbmsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_objectstorage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_objectstorageItemProvider tosca_nodes_objectstorageItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_objectstorage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_objectstorageAdapter() {
		if (tosca_nodes_objectstorageItemProvider == null) {
			tosca_nodes_objectstorageItemProvider = new Tosca_nodes_objectstorageItemProvider(this);
		}

		return tosca_nodes_objectstorageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_compute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_computeItemProvider tosca_nodes_computeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_compute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_computeAdapter() {
		if (tosca_nodes_computeItemProvider == null) {
			tosca_nodes_computeItemProvider = new Tosca_nodes_computeItemProvider(this);
		}

		return tosca_nodes_computeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_loadbalancer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_loadbalancerItemProvider tosca_nodes_loadbalancerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_loadbalancer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_loadbalancerAdapter() {
		if (tosca_nodes_loadbalancerItemProvider == null) {
			tosca_nodes_loadbalancerItemProvider = new Tosca_nodes_loadbalancerItemProvider(this);
		}

		return tosca_nodes_loadbalancerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_webserver} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_webserverItemProvider tosca_nodes_webserverItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_webserver}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_webserverAdapter() {
		if (tosca_nodes_webserverItemProvider == null) {
			tosca_nodes_webserverItemProvider = new Tosca_nodes_webserverItemProvider(this);
		}

		return tosca_nodes_webserverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_database} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_databaseItemProvider tosca_nodes_databaseItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_database}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_databaseAdapter() {
		if (tosca_nodes_databaseItemProvider == null) {
			tosca_nodes_databaseItemProvider = new Tosca_nodes_databaseItemProvider(this);
		}

		return tosca_nodes_databaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_container_application} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_container_applicationItemProvider tosca_nodes_container_applicationItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_container_application}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_container_applicationAdapter() {
		if (tosca_nodes_container_applicationItemProvider == null) {
			tosca_nodes_container_applicationItemProvider = new Tosca_nodes_container_applicationItemProvider(this);
		}

		return tosca_nodes_container_applicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_container_runtime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_container_runtimeItemProvider tosca_nodes_container_runtimeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_container_runtime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_container_runtimeAdapter() {
		if (tosca_nodes_container_runtimeItemProvider == null) {
			tosca_nodes_container_runtimeItemProvider = new Tosca_nodes_container_runtimeItemProvider(this);
		}

		return tosca_nodes_container_runtimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_blockstorage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_blockstorageItemProvider tosca_nodes_blockstorageItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_nodes_blockstorage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_blockstorageAdapter() {
		if (tosca_nodes_blockstorageItemProvider == null) {
			tosca_nodes_blockstorageItemProvider = new Tosca_nodes_blockstorageItemProvider(this);
		}

		return tosca_nodes_blockstorageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_policies_root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_policies_rootItemProvider tosca_policies_rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_policies_root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_policies_rootAdapter() {
		if (tosca_policies_rootItemProvider == null) {
			tosca_policies_rootItemProvider = new Tosca_policies_rootItemProvider(this);
		}

		return tosca_policies_rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_policies_update} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_policies_updateItemProvider tosca_policies_updateItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_policies_update}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_policies_updateAdapter() {
		if (tosca_policies_updateItemProvider == null) {
			tosca_policies_updateItemProvider = new Tosca_policies_updateItemProvider(this);
		}

		return tosca_policies_updateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_policies_placement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_policies_placementItemProvider tosca_policies_placementItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_policies_placement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_policies_placementAdapter() {
		if (tosca_policies_placementItemProvider == null) {
			tosca_policies_placementItemProvider = new Tosca_policies_placementItemProvider(this);
		}

		return tosca_policies_placementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_policies_scaling} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_policies_scalingItemProvider tosca_policies_scalingItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_policies_scaling}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_policies_scalingAdapter() {
		if (tosca_policies_scalingItemProvider == null) {
			tosca_policies_scalingItemProvider = new Tosca_policies_scalingItemProvider(this);
		}

		return tosca_policies_scalingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_policies_performance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_policies_performanceItemProvider tosca_policies_performanceItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_policies_performance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_policies_performanceAdapter() {
		if (tosca_policies_performanceItemProvider == null) {
			tosca_policies_performanceItemProvider = new Tosca_policies_performanceItemProvider(this);
		}

		return tosca_policies_performanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_groups_root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_groups_rootItemProvider tosca_groups_rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_groups_root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_groups_rootAdapter() {
		if (tosca_groups_rootItemProvider == null) {
			tosca_groups_rootItemProvider = new Tosca_groups_rootItemProvider(this);
		}

		return tosca_groups_rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_interfaces_root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_interfaces_rootItemProvider tosca_interfaces_rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_interfaces_root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_interfaces_rootAdapter() {
		if (tosca_interfaces_rootItemProvider == null) {
			tosca_interfaces_rootItemProvider = new Tosca_interfaces_rootItemProvider(this);
		}

		return tosca_interfaces_rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_interfaces_relationship_configure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_interfaces_relationship_configureItemProvider tosca_interfaces_relationship_configureItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_interfaces_relationship_configure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_interfaces_relationship_configureAdapter() {
		if (tosca_interfaces_relationship_configureItemProvider == null) {
			tosca_interfaces_relationship_configureItemProvider = new Tosca_interfaces_relationship_configureItemProvider(this);
		}

		return tosca_interfaces_relationship_configureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_interfaces_node_lifecycle_standard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_interfaces_node_lifecycle_standardItemProvider tosca_interfaces_node_lifecycle_standardItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_interfaces_node_lifecycle_standard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_interfaces_node_lifecycle_standardAdapter() {
		if (tosca_interfaces_node_lifecycle_standardItemProvider == null) {
			tosca_interfaces_node_lifecycle_standardItemProvider = new Tosca_interfaces_node_lifecycle_standardItemProvider(this);
		}

		return tosca_interfaces_node_lifecycle_standardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_rootItemProvider tosca_relationships_rootItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_rootAdapter() {
		if (tosca_relationships_rootItemProvider == null) {
			tosca_relationships_rootItemProvider = new Tosca_relationships_rootItemProvider(this);
		}

		return tosca_relationships_rootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_connectsto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_connectstoItemProvider tosca_relationships_connectstoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_connectsto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_connectstoAdapter() {
		if (tosca_relationships_connectstoItemProvider == null) {
			tosca_relationships_connectstoItemProvider = new Tosca_relationships_connectstoItemProvider(this);
		}

		return tosca_relationships_connectstoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_routesto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_routestoItemProvider tosca_relationships_routestoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_routesto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_routestoAdapter() {
		if (tosca_relationships_routestoItemProvider == null) {
			tosca_relationships_routestoItemProvider = new Tosca_relationships_routestoItemProvider(this);
		}

		return tosca_relationships_routestoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_attachesto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_attachestoItemProvider tosca_relationships_attachestoItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_attachesto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_attachestoAdapter() {
		if (tosca_relationships_attachestoItemProvider == null) {
			tosca_relationships_attachestoItemProvider = new Tosca_relationships_attachestoItemProvider(this);
		}

		return tosca_relationships_attachestoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_hostedon} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_hostedonItemProvider tosca_relationships_hostedonItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_hostedon}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_hostedonAdapter() {
		if (tosca_relationships_hostedonItemProvider == null) {
			tosca_relationships_hostedonItemProvider = new Tosca_relationships_hostedonItemProvider(this);
		}

		return tosca_relationships_hostedonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_dependson} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_dependsonItemProvider tosca_relationships_dependsonItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.cmf.occi.tosca.Tosca_relationships_dependson}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_dependsonAdapter() {
		if (tosca_relationships_dependsonItemProvider == null) {
			tosca_relationships_dependsonItemProvider = new Tosca_relationships_dependsonItemProvider(this);
		}

		return tosca_relationships_dependsonItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (arrayStringItemProvider != null) arrayStringItemProvider.dispose();
		if (arrayBooleanItemProvider != null) arrayBooleanItemProvider.dispose();
		if (arrayByteItemProvider != null) arrayByteItemProvider.dispose();
		if (arrayDoubleItemProvider != null) arrayDoubleItemProvider.dispose();
		if (arrayFloatItemProvider != null) arrayFloatItemProvider.dispose();
		if (arrayIntegerItemProvider != null) arrayIntegerItemProvider.dispose();
		if (arrayLongItemProvider != null) arrayLongItemProvider.dispose();
		if (arrayShortItemProvider != null) arrayShortItemProvider.dispose();
		if (toscadatatypesnetworkNetworkInfoItemProvider != null) toscadatatypesnetworkNetworkInfoItemProvider.dispose();
		if (toscadatatypesnetworkPortInfoItemProvider != null) toscadatatypesnetworkPortInfoItemProvider.dispose();
		if (toscadatatypesCredentialItemProvider != null) toscadatatypesCredentialItemProvider.dispose();
		if (toscadatatypesnetworkPortSpecItemProvider != null) toscadatatypesnetworkPortSpecItemProvider.dispose();
		if (tosca_capabilities_rootItemProvider != null) tosca_capabilities_rootItemProvider.dispose();
		if (tosca_capabilities_nodeItemProvider != null) tosca_capabilities_nodeItemProvider.dispose();
		if (tosca_capabilities_endpointItemProvider != null) tosca_capabilities_endpointItemProvider.dispose();
		if (tosca_capabilities_scalableItemProvider != null) tosca_capabilities_scalableItemProvider.dispose();
		if (tosca_capabilities_network_bindableItemProvider != null) tosca_capabilities_network_bindableItemProvider.dispose();
		if (tosca_capabilities_containerItemProvider != null) tosca_capabilities_containerItemProvider.dispose();
		if (tosca_capabilities_endpoint_databaseItemProvider != null) tosca_capabilities_endpoint_databaseItemProvider.dispose();
		if (tosca_capabilities_endpoint_publicItemProvider != null) tosca_capabilities_endpoint_publicItemProvider.dispose();
		if (tosca_capabilities_endpoint_adminItemProvider != null) tosca_capabilities_endpoint_adminItemProvider.dispose();
		if (tosca_capabilities_operatingsystemItemProvider != null) tosca_capabilities_operatingsystemItemProvider.dispose();
		if (tosca_capabilities_attachmentItemProvider != null) tosca_capabilities_attachmentItemProvider.dispose();
		if (tosca_nodes_rootItemProvider != null) tosca_nodes_rootItemProvider.dispose();
		if (tosca_nodes_webapplicationItemProvider != null) tosca_nodes_webapplicationItemProvider.dispose();
		if (tosca_nodes_softwarecomponentItemProvider != null) tosca_nodes_softwarecomponentItemProvider.dispose();
		if (tosca_nodes_dbmsItemProvider != null) tosca_nodes_dbmsItemProvider.dispose();
		if (tosca_nodes_objectstorageItemProvider != null) tosca_nodes_objectstorageItemProvider.dispose();
		if (tosca_nodes_computeItemProvider != null) tosca_nodes_computeItemProvider.dispose();
		if (tosca_nodes_loadbalancerItemProvider != null) tosca_nodes_loadbalancerItemProvider.dispose();
		if (tosca_nodes_webserverItemProvider != null) tosca_nodes_webserverItemProvider.dispose();
		if (tosca_nodes_databaseItemProvider != null) tosca_nodes_databaseItemProvider.dispose();
		if (tosca_nodes_container_applicationItemProvider != null) tosca_nodes_container_applicationItemProvider.dispose();
		if (tosca_nodes_container_runtimeItemProvider != null) tosca_nodes_container_runtimeItemProvider.dispose();
		if (tosca_nodes_blockstorageItemProvider != null) tosca_nodes_blockstorageItemProvider.dispose();
		if (tosca_policies_rootItemProvider != null) tosca_policies_rootItemProvider.dispose();
		if (tosca_policies_updateItemProvider != null) tosca_policies_updateItemProvider.dispose();
		if (tosca_policies_placementItemProvider != null) tosca_policies_placementItemProvider.dispose();
		if (tosca_policies_scalingItemProvider != null) tosca_policies_scalingItemProvider.dispose();
		if (tosca_policies_performanceItemProvider != null) tosca_policies_performanceItemProvider.dispose();
		if (tosca_groups_rootItemProvider != null) tosca_groups_rootItemProvider.dispose();
		if (tosca_interfaces_rootItemProvider != null) tosca_interfaces_rootItemProvider.dispose();
		if (tosca_interfaces_relationship_configureItemProvider != null) tosca_interfaces_relationship_configureItemProvider.dispose();
		if (tosca_interfaces_node_lifecycle_standardItemProvider != null) tosca_interfaces_node_lifecycle_standardItemProvider.dispose();
		if (tosca_relationships_rootItemProvider != null) tosca_relationships_rootItemProvider.dispose();
		if (tosca_relationships_connectstoItemProvider != null) tosca_relationships_connectstoItemProvider.dispose();
		if (tosca_relationships_routestoItemProvider != null) tosca_relationships_routestoItemProvider.dispose();
		if (tosca_relationships_attachestoItemProvider != null) tosca_relationships_attachestoItemProvider.dispose();
		if (tosca_relationships_hostedonItemProvider != null) tosca_relationships_hostedonItemProvider.dispose();
		if (tosca_relationships_dependsonItemProvider != null) tosca_relationships_dependsonItemProvider.dispose();
	}

}
