/**
 * Copyright (c) 2015-2017 Obeo, Inria
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 	
 * Contributors:
 * - William Piers <william.piers@obeo.fr>
 * - Philippe Merle <philippe.merle@inria.fr>
 * - Faiez Zalila <faiez.zalila@inria.fr>
 */
package extendedtosca.provider;

import extendedtosca.util.ExtendedtoscaAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ExtendedtoscaItemProviderAdapterFactory extends ExtendedtoscaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ExtendedtoscaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.arrayCredential} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayCredentialItemProvider arrayCredentialItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.arrayCredential}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayCredentialAdapter() {
		if (arrayCredentialItemProvider == null) {
			arrayCredentialItemProvider = new arrayCredentialItemProvider(this);
		}

		return arrayCredentialItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.arrayPortSpec} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayPortSpecItemProvider arrayPortSpecItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.arrayPortSpec}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayPortSpecAdapter() {
		if (arrayPortSpecItemProvider == null) {
			arrayPortSpecItemProvider = new arrayPortSpecItemProvider(this);
		}

		return arrayPortSpecItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.arrayversion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayversionItemProvider arrayversionItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.arrayversion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayversionAdapter() {
		if (arrayversionItemProvider == null) {
			arrayversionItemProvider = new arrayversionItemProvider(this);
		}

		return arrayversionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.arrayinteger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected arrayintegerItemProvider arrayintegerItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.arrayinteger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createarrayintegerAdapter() {
		if (arrayintegerItemProvider == null) {
			arrayintegerItemProvider = new arrayintegerItemProvider(this);
		}

		return arrayintegerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_capabilities_somecap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_somecapItemProvider tosca_capabilities_somecapItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_capabilities_somecap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_somecapAdapter() {
		if (tosca_capabilities_somecapItemProvider == null) {
			tosca_capabilities_somecapItemProvider = new Tosca_capabilities_somecapItemProvider(this);
		}

		return tosca_capabilities_somecapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_capabilities_indigo_endpoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_indigo_endpointItemProvider tosca_capabilities_indigo_endpointItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_capabilities_indigo_endpoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_indigo_endpointAdapter() {
		if (tosca_capabilities_indigo_endpointItemProvider == null) {
			tosca_capabilities_indigo_endpointItemProvider = new Tosca_capabilities_indigo_endpointItemProvider(this);
		}

		return tosca_capabilities_indigo_endpointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_capabilities_ha} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_haItemProvider tosca_capabilities_haItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_capabilities_ha}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_haAdapter() {
		if (tosca_capabilities_haItemProvider == null) {
			tosca_capabilities_haItemProvider = new Tosca_capabilities_haItemProvider(this);
		}

		return tosca_capabilities_haItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_capabilities_container_docker} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_container_dockerItemProvider tosca_capabilities_container_dockerItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_capabilities_container_docker}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_container_dockerAdapter() {
		if (tosca_capabilities_container_dockerItemProvider == null) {
			tosca_capabilities_container_dockerItemProvider = new Tosca_capabilities_container_dockerItemProvider(this);
		}

		return tosca_capabilities_container_dockerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_capabilities_containerchild} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_containerchildItemProvider tosca_capabilities_containerchildItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_capabilities_containerchild}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_containerchildAdapter() {
		if (tosca_capabilities_containerchildItemProvider == null) {
			tosca_capabilities_containerchildItemProvider = new Tosca_capabilities_containerchildItemProvider(this);
		}

		return tosca_capabilities_containerchildItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_capabilities_somechildcap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_capabilities_somechildcapItemProvider tosca_capabilities_somechildcapItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_capabilities_somechildcap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_capabilities_somechildcapAdapter() {
		if (tosca_capabilities_somechildcapItemProvider == null) {
			tosca_capabilities_somechildcapItemProvider = new Tosca_capabilities_somechildcapItemProvider(this);
		}

		return tosca_capabilities_somechildcapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_computewithprop} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_computewithpropItemProvider tosca_nodes_computewithpropItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_computewithprop}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_computewithpropAdapter() {
		if (tosca_nodes_computewithpropItemProvider == null) {
			tosca_nodes_computewithpropItemProvider = new Tosca_nodes_computewithpropItemProvider(this);
		}

		return tosca_nodes_computewithpropItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_webapplication_paypalpizzastore} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_webapplication_paypalpizzastoreItemProvider tosca_nodes_webapplication_paypalpizzastoreItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_webapplication_paypalpizzastore}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_webapplication_paypalpizzastoreAdapter() {
		if (tosca_nodes_webapplication_paypalpizzastoreItemProvider == null) {
			tosca_nodes_webapplication_paypalpizzastoreItemProvider = new Tosca_nodes_webapplication_paypalpizzastoreItemProvider(this);
		}

		return tosca_nodes_webapplication_paypalpizzastoreItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_network_network} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_network_networkItemProvider tosca_nodes_network_networkItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_network_network}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_network_networkAdapter() {
		if (tosca_nodes_network_networkItemProvider == null) {
			tosca_nodes_network_networkItemProvider = new Tosca_nodes_network_networkItemProvider(this);
		}

		return tosca_nodes_network_networkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_container_application_docker} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_container_application_dockerItemProvider tosca_nodes_container_application_dockerItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_container_application_docker}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_container_application_dockerAdapter() {
		if (tosca_nodes_container_application_dockerItemProvider == null) {
			tosca_nodes_container_application_dockerItemProvider = new Tosca_nodes_container_application_dockerItemProvider(this);
		}

		return tosca_nodes_container_application_dockerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_softwarecomponent_kibana} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_softwarecomponent_kibanaItemProvider tosca_nodes_softwarecomponent_kibanaItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_softwarecomponent_kibana}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_softwarecomponent_kibanaAdapter() {
		if (tosca_nodes_softwarecomponent_kibanaItemProvider == null) {
			tosca_nodes_softwarecomponent_kibanaItemProvider = new Tosca_nodes_softwarecomponent_kibanaItemProvider(this);
		}

		return tosca_nodes_softwarecomponent_kibanaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_computewithattrlist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_computewithattrlistItemProvider tosca_nodes_computewithattrlistItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_computewithattrlist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_computewithattrlistAdapter() {
		if (tosca_nodes_computewithattrlistItemProvider == null) {
			tosca_nodes_computewithattrlistItemProvider = new Tosca_nodes_computewithattrlistItemProvider(this);
		}

		return tosca_nodes_computewithattrlistItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_softwarecomponent_logstash} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_softwarecomponent_logstashItemProvider tosca_nodes_softwarecomponent_logstashItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_softwarecomponent_logstash}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_softwarecomponent_logstashAdapter() {
		if (tosca_nodes_softwarecomponent_logstashItemProvider == null) {
			tosca_nodes_softwarecomponent_logstashItemProvider = new Tosca_nodes_softwarecomponent_logstashItemProvider(this);
		}

		return tosca_nodes_softwarecomponent_logstashItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Example_databasesubsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Example_databasesubsystemItemProvider example_databasesubsystemItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Example_databasesubsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExample_databasesubsystemAdapter() {
		if (example_databasesubsystemItemProvider == null) {
			example_databasesubsystemItemProvider = new Example_databasesubsystemItemProvider(this);
		}

		return example_databasesubsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_softwarecomponent_collectd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_softwarecomponent_collectdItemProvider tosca_nodes_softwarecomponent_collectdItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_softwarecomponent_collectd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_softwarecomponent_collectdAdapter() {
		if (tosca_nodes_softwarecomponent_collectdItemProvider == null) {
			tosca_nodes_softwarecomponent_collectdItemProvider = new Tosca_nodes_softwarecomponent_collectdItemProvider(this);
		}

		return tosca_nodes_softwarecomponent_collectdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_nodewithreq} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_nodewithreqItemProvider tosca_nodes_nodewithreqItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_nodewithreq}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_nodewithreqAdapter() {
		if (tosca_nodes_nodewithreqItemProvider == null) {
			tosca_nodes_nodewithreqItemProvider = new Tosca_nodes_nodewithreqItemProvider(this);
		}

		return tosca_nodes_nodewithreqItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_somenode2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_somenode2ItemProvider tosca_nodes_somenode2ItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_somenode2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_somenode2Adapter() {
		if (tosca_nodes_somenode2ItemProvider == null) {
			tosca_nodes_somenode2ItemProvider = new Tosca_nodes_somenode2ItemProvider(this);
		}

		return tosca_nodes_somenode2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_php} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_phpItemProvider tosca_nodes_phpItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_php}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_phpAdapter() {
		if (tosca_nodes_phpItemProvider == null) {
			tosca_nodes_phpItemProvider = new Tosca_nodes_phpItemProvider(this);
		}

		return tosca_nodes_phpItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_database_mysql} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_database_mysqlItemProvider tosca_nodes_database_mysqlItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_database_mysql}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_database_mysqlAdapter() {
		if (tosca_nodes_database_mysqlItemProvider == null) {
			tosca_nodes_database_mysqlItemProvider = new Tosca_nodes_database_mysqlItemProvider(this);
		}

		return tosca_nodes_database_mysqlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Example_queuingsubsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Example_queuingsubsystemItemProvider example_queuingsubsystemItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Example_queuingsubsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExample_queuingsubsystemAdapter() {
		if (example_queuingsubsystemItemProvider == null) {
			example_queuingsubsystemItemProvider = new Example_queuingsubsystemItemProvider(this);
		}

		return example_queuingsubsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Example_transactionsubsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Example_transactionsubsystemItemProvider example_transactionsubsystemItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Example_transactionsubsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExample_transactionsubsystemAdapter() {
		if (example_transactionsubsystemItemProvider == null) {
			example_transactionsubsystemItemProvider = new Example_transactionsubsystemItemProvider(this);
		}

		return example_transactionsubsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_abstractmysql} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_abstractmysqlItemProvider tosca_nodes_abstractmysqlItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_abstractmysql}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_abstractmysqlAdapter() {
		if (tosca_nodes_abstractmysqlItemProvider == null) {
			tosca_nodes_abstractmysqlItemProvider = new Tosca_nodes_abstractmysqlItemProvider(this);
		}

		return tosca_nodes_abstractmysqlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_mysql} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_mysqlItemProvider tosca_nodes_mysqlItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_mysql}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_mysqlAdapter() {
		if (tosca_nodes_mysqlItemProvider == null) {
			tosca_nodes_mysqlItemProvider = new Tosca_nodes_mysqlItemProvider(this);
		}

		return tosca_nodes_mysqlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_softwarecomponent_elasticsearch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_softwarecomponent_elasticsearchItemProvider tosca_nodes_softwarecomponent_elasticsearchItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_softwarecomponent_elasticsearch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_softwarecomponent_elasticsearchAdapter() {
		if (tosca_nodes_softwarecomponent_elasticsearchItemProvider == null) {
			tosca_nodes_softwarecomponent_elasticsearchItemProvider = new Tosca_nodes_softwarecomponent_elasticsearchItemProvider(this);
		}

		return tosca_nodes_softwarecomponent_elasticsearchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_databasewithlistparam} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_databasewithlistparamItemProvider tosca_nodes_databasewithlistparamItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_databasewithlistparam}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_databasewithlistparamAdapter() {
		if (tosca_nodes_databasewithlistparamItemProvider == null) {
			tosca_nodes_databasewithlistparamItemProvider = new Tosca_nodes_databasewithlistparamItemProvider(this);
		}

		return tosca_nodes_databasewithlistparamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Example_someapp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Example_someappItemProvider example_someappItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Example_someapp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExample_someappAdapter() {
		if (example_someappItemProvider == null) {
			example_someappItemProvider = new Example_someappItemProvider(this);
		}

		return example_someappItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_nodewithcap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_nodewithcapItemProvider tosca_nodes_nodewithcapItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_nodewithcap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_nodewithcapAdapter() {
		if (tosca_nodes_nodewithcapItemProvider == null) {
			tosca_nodes_nodewithcapItemProvider = new Tosca_nodes_nodewithcapItemProvider(this);
		}

		return tosca_nodes_nodewithcapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_apache} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_apacheItemProvider tosca_nodes_apacheItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_apache}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_apacheAdapter() {
		if (tosca_nodes_apacheItemProvider == null) {
			tosca_nodes_apacheItemProvider = new Tosca_nodes_apacheItemProvider(this);
		}

		return tosca_nodes_apacheItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Rsyslog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RsyslogItemProvider rsyslogItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Rsyslog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRsyslogAdapter() {
		if (rsyslogItemProvider == null) {
			rsyslogItemProvider = new RsyslogItemProvider(this);
		}

		return rsyslogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_wordpress} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_wordpressItemProvider tosca_nodes_wordpressItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_wordpress}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_wordpressAdapter() {
		if (tosca_nodes_wordpressItemProvider == null) {
			tosca_nodes_wordpressItemProvider = new Tosca_nodes_wordpressItemProvider(this);
		}

		return tosca_nodes_wordpressItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_network_port} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_network_portItemProvider tosca_nodes_network_portItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_network_port}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_network_portAdapter() {
		if (tosca_nodes_network_portItemProvider == null) {
			tosca_nodes_network_portItemProvider = new Tosca_nodes_network_portItemProvider(this);
		}

		return tosca_nodes_network_portItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_computewithcapwithattr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_computewithcapwithattrItemProvider tosca_nodes_computewithcapwithattrItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_computewithcapwithattr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_computewithcapwithattrAdapter() {
		if (tosca_nodes_computewithcapwithattrItemProvider == null) {
			tosca_nodes_computewithcapwithattrItemProvider = new Tosca_nodes_computewithcapwithattrItemProvider(this);
		}

		return tosca_nodes_computewithcapwithattrItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_softwarecomponent_rsyslog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_softwarecomponent_rsyslogItemProvider tosca_nodes_softwarecomponent_rsyslogItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_softwarecomponent_rsyslog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_softwarecomponent_rsyslogAdapter() {
		if (tosca_nodes_softwarecomponent_rsyslogItemProvider == null) {
			tosca_nodes_softwarecomponent_rsyslogItemProvider = new Tosca_nodes_softwarecomponent_rsyslogItemProvider(this);
		}

		return tosca_nodes_softwarecomponent_rsyslogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_hacompute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_hacomputeItemProvider tosca_nodes_hacomputeItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_hacompute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_hacomputeAdapter() {
		if (tosca_nodes_hacomputeItemProvider == null) {
			tosca_nodes_hacomputeItemProvider = new Tosca_nodes_hacomputeItemProvider(this);
		}

		return tosca_nodes_hacomputeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_somenode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_somenodeItemProvider tosca_nodes_somenodeItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_somenode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_somenodeAdapter() {
		if (tosca_nodes_somenodeItemProvider == null) {
			tosca_nodes_somenodeItemProvider = new Tosca_nodes_somenodeItemProvider(this);
		}

		return tosca_nodes_somenodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_webserver_nodejs} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_webserver_nodejsItemProvider tosca_nodes_webserver_nodejsItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_webserver_nodejs}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_webserver_nodejsAdapter() {
		if (tosca_nodes_webserver_nodejsItemProvider == null) {
			tosca_nodes_webserver_nodejsItemProvider = new Tosca_nodes_webserver_nodejsItemProvider(this);
		}

		return tosca_nodes_webserver_nodejsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_nodes_dbms_mysql} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_nodes_dbms_mysqlItemProvider tosca_nodes_dbms_mysqlItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_nodes_dbms_mysql}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_nodes_dbms_mysqlAdapter() {
		if (tosca_nodes_dbms_mysqlItemProvider == null) {
			tosca_nodes_dbms_mysqlItemProvider = new Tosca_nodes_dbms_mysqlItemProvider(this);
		}

		return tosca_nodes_dbms_mysqlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Mycompany_mytypes_myscalingpolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Mycompany_mytypes_myscalingpolicyItemProvider mycompany_mytypes_myscalingpolicyItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Mycompany_mytypes_myscalingpolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMycompany_mytypes_myscalingpolicyAdapter() {
		if (mycompany_mytypes_myscalingpolicyItemProvider == null) {
			mycompany_mytypes_myscalingpolicyItemProvider = new Mycompany_mytypes_myscalingpolicyItemProvider(this);
		}

		return mycompany_mytypes_myscalingpolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Test_relation_connects} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Test_relation_connectsItemProvider test_relation_connectsItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Test_relation_connects}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTest_relation_connectsAdapter() {
		if (test_relation_connectsItemProvider == null) {
			test_relation_connectsItemProvider = new Test_relation_connectsItemProvider(this);
		}

		return test_relation_connectsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_relationships_network_bindsto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_network_bindstoItemProvider tosca_relationships_network_bindstoItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_relationships_network_bindsto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_network_bindstoAdapter() {
		if (tosca_relationships_network_bindstoItemProvider == null) {
			tosca_relationships_network_bindstoItemProvider = new Tosca_relationships_network_bindstoItemProvider(this);
		}

		return tosca_relationships_network_bindstoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_relationships_ha} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_haItemProvider tosca_relationships_haItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_relationships_ha}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_haAdapter() {
		if (tosca_relationships_haItemProvider == null) {
			tosca_relationships_haItemProvider = new Tosca_relationships_haItemProvider(this);
		}

		return tosca_relationships_haItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Myattachesto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MyattachestoItemProvider myattachestoItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Myattachesto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMyattachestoAdapter() {
		if (myattachestoItemProvider == null) {
			myattachestoItemProvider = new MyattachestoItemProvider(this);
		}

		return myattachestoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link extendedtosca.Tosca_relationships_network_linksto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Tosca_relationships_network_linkstoItemProvider tosca_relationships_network_linkstoItemProvider;

	/**
	 * This creates an adapter for a {@link extendedtosca.Tosca_relationships_network_linksto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTosca_relationships_network_linkstoAdapter() {
		if (tosca_relationships_network_linkstoItemProvider == null) {
			tosca_relationships_network_linkstoItemProvider = new Tosca_relationships_network_linkstoItemProvider(this);
		}

		return tosca_relationships_network_linkstoItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (arrayCredentialItemProvider != null) arrayCredentialItemProvider.dispose();
		if (arrayPortSpecItemProvider != null) arrayPortSpecItemProvider.dispose();
		if (arrayversionItemProvider != null) arrayversionItemProvider.dispose();
		if (arrayintegerItemProvider != null) arrayintegerItemProvider.dispose();
		if (tosca_capabilities_somecapItemProvider != null) tosca_capabilities_somecapItemProvider.dispose();
		if (tosca_capabilities_indigo_endpointItemProvider != null) tosca_capabilities_indigo_endpointItemProvider.dispose();
		if (tosca_capabilities_haItemProvider != null) tosca_capabilities_haItemProvider.dispose();
		if (tosca_capabilities_container_dockerItemProvider != null) tosca_capabilities_container_dockerItemProvider.dispose();
		if (tosca_capabilities_containerchildItemProvider != null) tosca_capabilities_containerchildItemProvider.dispose();
		if (tosca_capabilities_somechildcapItemProvider != null) tosca_capabilities_somechildcapItemProvider.dispose();
		if (tosca_nodes_computewithpropItemProvider != null) tosca_nodes_computewithpropItemProvider.dispose();
		if (tosca_nodes_webapplication_paypalpizzastoreItemProvider != null) tosca_nodes_webapplication_paypalpizzastoreItemProvider.dispose();
		if (tosca_nodes_network_networkItemProvider != null) tosca_nodes_network_networkItemProvider.dispose();
		if (tosca_nodes_container_application_dockerItemProvider != null) tosca_nodes_container_application_dockerItemProvider.dispose();
		if (tosca_nodes_softwarecomponent_kibanaItemProvider != null) tosca_nodes_softwarecomponent_kibanaItemProvider.dispose();
		if (tosca_nodes_computewithattrlistItemProvider != null) tosca_nodes_computewithattrlistItemProvider.dispose();
		if (tosca_nodes_softwarecomponent_logstashItemProvider != null) tosca_nodes_softwarecomponent_logstashItemProvider.dispose();
		if (example_databasesubsystemItemProvider != null) example_databasesubsystemItemProvider.dispose();
		if (tosca_nodes_softwarecomponent_collectdItemProvider != null) tosca_nodes_softwarecomponent_collectdItemProvider.dispose();
		if (tosca_nodes_nodewithreqItemProvider != null) tosca_nodes_nodewithreqItemProvider.dispose();
		if (tosca_nodes_somenode2ItemProvider != null) tosca_nodes_somenode2ItemProvider.dispose();
		if (tosca_nodes_phpItemProvider != null) tosca_nodes_phpItemProvider.dispose();
		if (tosca_nodes_database_mysqlItemProvider != null) tosca_nodes_database_mysqlItemProvider.dispose();
		if (example_queuingsubsystemItemProvider != null) example_queuingsubsystemItemProvider.dispose();
		if (example_transactionsubsystemItemProvider != null) example_transactionsubsystemItemProvider.dispose();
		if (tosca_nodes_abstractmysqlItemProvider != null) tosca_nodes_abstractmysqlItemProvider.dispose();
		if (tosca_nodes_mysqlItemProvider != null) tosca_nodes_mysqlItemProvider.dispose();
		if (tosca_nodes_softwarecomponent_elasticsearchItemProvider != null) tosca_nodes_softwarecomponent_elasticsearchItemProvider.dispose();
		if (tosca_nodes_databasewithlistparamItemProvider != null) tosca_nodes_databasewithlistparamItemProvider.dispose();
		if (example_someappItemProvider != null) example_someappItemProvider.dispose();
		if (tosca_nodes_nodewithcapItemProvider != null) tosca_nodes_nodewithcapItemProvider.dispose();
		if (tosca_nodes_apacheItemProvider != null) tosca_nodes_apacheItemProvider.dispose();
		if (rsyslogItemProvider != null) rsyslogItemProvider.dispose();
		if (tosca_nodes_wordpressItemProvider != null) tosca_nodes_wordpressItemProvider.dispose();
		if (tosca_nodes_network_portItemProvider != null) tosca_nodes_network_portItemProvider.dispose();
		if (tosca_nodes_computewithcapwithattrItemProvider != null) tosca_nodes_computewithcapwithattrItemProvider.dispose();
		if (tosca_nodes_softwarecomponent_rsyslogItemProvider != null) tosca_nodes_softwarecomponent_rsyslogItemProvider.dispose();
		if (tosca_nodes_hacomputeItemProvider != null) tosca_nodes_hacomputeItemProvider.dispose();
		if (tosca_nodes_somenodeItemProvider != null) tosca_nodes_somenodeItemProvider.dispose();
		if (tosca_nodes_webserver_nodejsItemProvider != null) tosca_nodes_webserver_nodejsItemProvider.dispose();
		if (tosca_nodes_dbms_mysqlItemProvider != null) tosca_nodes_dbms_mysqlItemProvider.dispose();
		if (mycompany_mytypes_myscalingpolicyItemProvider != null) mycompany_mytypes_myscalingpolicyItemProvider.dispose();
		if (test_relation_connectsItemProvider != null) test_relation_connectsItemProvider.dispose();
		if (tosca_relationships_network_bindstoItemProvider != null) tosca_relationships_network_bindstoItemProvider.dispose();
		if (tosca_relationships_haItemProvider != null) tosca_relationships_haItemProvider.dispose();
		if (myattachestoItemProvider != null) myattachestoItemProvider.dispose();
		if (tosca_relationships_network_linkstoItemProvider != null) tosca_relationships_network_linkstoItemProvider.dispose();
	}

}
